[build]
    command = "yarn run build"
[dev]
    command = "yarn run start"
[build.processing]
    skip_processing = true
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[[plugins]]
    package = "@netlify/plugin-nextjs"